import type { AiModelCard } from '../types/aiModel'

/**
 * OpenAI 自配服务商模型 + USD 官方价量级（用于用量展示 / 成本估算，不扣 PureChat 积分）。
 * 阶梯/查表定价取首档单价；可按官方价再 diff。
 * 按 releasedAt 降序保留最近 25 个 chat 模型。
 */
export const openaiChatModels: AiModelCard[] = [
  {
    id: 'gpt-5.6-luna',
    displayName: 'GPT-5.6 Luna',
    description: 'GPT-5.6 Luna 面向成本敏感的高并发场景优化，是 GPT-5.6 系列中单价最低的型号。',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.6',
    contextWindowTokens: 1_050_000,
    maxOutput: 128_000,
    releasedAt: '2026-07-09',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1,
      textOutput: 6,
      textInputCacheRead: 0.1,
      textInputCacheWrite: 1.25,
    },
  },
  {
    id: 'gpt-5.6-sol',
    displayName: 'GPT-5.6 Sol',
    description: 'GPT-5.6 Sol 是 OpenAI 面向复杂推理、编程与长程智能体任务的前沿模型；gpt-5.6 别名会路由到 Sol。',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.6',
    contextWindowTokens: 1_050_000,
    maxOutput: 128_000,
    releasedAt: '2026-07-09',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 5,
      textOutput: 30,
      textInputCacheRead: 0.5,
      textInputCacheWrite: 6.25,
    },
  },
  {
    id: 'gpt-5.6-terra',
    displayName: 'GPT-5.6 Terra',
    description: 'GPT-5.6 Terra 在智能水平与成本之间取得平衡，面向日常专业工作，能力接近 GPT-5.5 而价格约为一半。',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.6',
    contextWindowTokens: 1_050_000,
    maxOutput: 128_000,
    releasedAt: '2026-07-09',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 2.5,
      textOutput: 15,
      textInputCacheRead: 0.25,
      textInputCacheWrite: 3.125,
    },
  },
  {
    id: 'chat-latest',
    displayName: 'Chat Latest',
    description: 'ChatGPT 使用的最新即时模型。',
    enabled: false,
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2026-05-05',
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 5,
      textOutput: 30,
      textInputCacheRead: 0.5,
    },
  },
  {
    id: 'gpt-5.5',
    displayName: 'GPT-5.5',
    description: 'GPT-5.5 是我们最新的前沿模型，适用于最复杂的专业工作。',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.5',
    contextWindowTokens: 1_050_000,
    maxOutput: 128_000,
    releasedAt: '2026-04-23',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 5,
      textOutput: 30,
      textInputCacheRead: 0.5,
    },
  },
  {
    id: 'gpt-5.5-pro',
    displayName: 'GPT-5.5 Pro',
    description: 'GPT-5.5 Pro 通过更高计算投入实现更深入思考，并持续输出更可靠的答案。',
    family: 'gpt',
    generation: 'gpt-5.5',
    contextWindowTokens: 1_050_000,
    maxOutput: 128_000,
    releasedAt: '2026-04-23',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 30,
      textOutput: 180,
    },
  },
  {
    id: 'gpt-5.4-mini',
    displayName: 'GPT-5.4 mini',
    description: 'OpenAI 的 GPT-5.4 Mini —— 性能与成本的高效平衡。',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.4',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2026-03-18',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 0.75,
      textOutput: 4.5,
      textInputCacheRead: 0.075,
    },
  },
  {
    id: 'gpt-5.4-nano',
    displayName: 'GPT-5.4 nano',
    description: 'OpenAI 的 GPT-5.4 Nano —— 超轻量模型，适用于高吞吐任务。',
    family: 'gpt',
    generation: 'gpt-5.4',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2026-03-18',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 0.2,
      textOutput: 1.25,
      textInputCacheRead: 0.02,
    },
  },
  {
    id: 'gpt-5.4',
    displayName: 'GPT-5.4',
    description: 'OpenAI 的 GPT-5.4 —— 新一代模型，支持百万级上下文与多模态输入。',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.4',
    contextWindowTokens: 1_050_000,
    maxOutput: 128_000,
    releasedAt: '2026-03-05',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 2.5,
      textOutput: 15,
      textInputCacheRead: 0.25,
    },
  },
  {
    id: 'gpt-5.4-pro',
    displayName: 'GPT-5.4 Pro',
    description: 'OpenAI 的 GPT-5.4 Pro —— 具备最大上下文与推理能力的高端模型。',
    family: 'gpt',
    generation: 'gpt-5.4',
    contextWindowTokens: 1_050_000,
    maxOutput: 128_000,
    releasedAt: '2026-03-05',
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 30,
      textOutput: 180,
    },
  },
  {
    id: 'gpt-5.3-chat-latest',
    displayName: 'GPT-5.3 Chat',
    description: 'GPT-5.3 Chat 是最新的 ChatGPT 模型，改进了对话体验。',
    family: 'gpt',
    generation: 'gpt-5.3',
    contextWindowTokens: 128_000,
    maxOutput: 16_384,
    releasedAt: '2026-03-04',
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.75,
      textOutput: 14,
      textInputCacheRead: 0.175,
    },
  },
  {
    id: 'gpt-5.3-codex',
    displayName: 'GPT-5.3 Codex',
    description: 'OpenAI 的 GPT-5.3 Codex —— 新一代 Codex，具备更强代码理解能力。',
    family: 'gpt',
    generation: 'gpt-5.3',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2026-02-05',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.75,
      textOutput: 14,
      textInputCacheRead: 0.175,
    },
  },
  {
    id: 'gpt-5.2-codex',
    displayName: 'GPT-5.2 Codex',
    description: 'OpenAI 的 GPT-5.2 Codex —— 工具调用准确度更高的代码专项模型。',
    family: 'gpt',
    generation: 'gpt-5.2',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2025-12-18',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.75,
      textOutput: 14,
      textInputCacheRead: 0.175,
    },
  },
  {
    id: 'gpt-5.2',
    displayName: 'GPT-5.2',
    description: 'OpenAI 的 GPT-5.2 —— 推理与多模态处理能力全面升级。',
    family: 'gpt',
    generation: 'gpt-5.2',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2025-12-11',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.75,
      textOutput: 14,
      textInputCacheRead: 0.175,
    },
  },
  {
    id: 'gpt-5.2-chat-latest',
    displayName: 'GPT-5.2 Chat',
    description: 'GPT-5.2 Chat 是 ChatGPT 的最新对话版本，带来最新的对话体验改进。',
    family: 'gpt',
    generation: 'gpt-5.2',
    contextWindowTokens: 128_000,
    maxOutput: 16_384,
    releasedAt: '2025-12-11',
    abilities: {
      functionCall: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.75,
      textOutput: 14,
      textInputCacheRead: 0.175,
    },
  },
  {
    id: 'gpt-5.2-pro',
    displayName: 'GPT-5.2 pro',
    description: 'GPT-5.2 Pro：更智能、更精准的 GPT-5.2 变体（仅限 Responses API），适用于复杂问题和多轮推理。',
    family: 'gpt',
    generation: 'gpt-5.2',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2025-12-11',
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 21,
      textOutput: 168,
    },
  },
  {
    id: 'gpt-5.1-codex-max',
    displayName: 'GPT-5.1 Codex Max',
    description: 'OpenAI 的 GPT-5.1 Codex Max —— 最高性能的 Codex 变体。',
    family: 'gpt',
    generation: 'gpt-5.1',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2025-12-04',
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.25,
      textOutput: 10,
      textInputCacheRead: 0.125,
    },
  },
  {
    id: 'gpt-5.1',
    displayName: 'GPT-5.1',
    description: 'OpenAI 的 GPT-5.1 —— 推理准确度进一步提升的改进版 GPT-5。',
    family: 'gpt',
    generation: 'gpt-5.1',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2025-11-13',
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.25,
      textOutput: 10,
      textInputCacheRead: 0.125,
    },
  },
  {
    id: 'gpt-5.1-chat-latest',
    displayName: 'GPT-5.1 Chat',
    description: 'GPT-5.1 Chat：GPT-5.1 的 ChatGPT 变体，专为对话场景打造。',
    family: 'gpt',
    generation: 'gpt-5.1',
    contextWindowTokens: 128_000,
    maxOutput: 16_384,
    releasedAt: '2025-11-13',
    abilities: {
      functionCall: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.25,
      textOutput: 10,
      textInputCacheRead: 0.125,
    },
  },
  {
    id: 'gpt-5.1-codex',
    displayName: 'GPT-5.1 Codex',
    description: 'OpenAI 的 GPT-5.1 Codex —— 加强工具调用的代码专项模型。',
    family: 'gpt',
    generation: 'gpt-5.1',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2025-11-13',
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.25,
      textOutput: 10,
      textInputCacheRead: 0.125,
    },
  },
  {
    id: 'gpt-5.1-codex-mini',
    displayName: 'GPT-5.1 Codex mini',
    description: 'OpenAI 的 GPT-5.1 Codex Mini —— 小型但强大的编码模型。',
    family: 'gpt',
    generation: 'gpt-5.1',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2025-11-13',
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 0.25,
      textOutput: 2,
      textInputCacheRead: 0.025,
    },
  },
  {
    id: 'gpt-5-pro',
    displayName: 'GPT-5 pro',
    description: 'GPT-5 Pro 使用更多计算资源以实现更深入的思考，持续提供更优质的答案。',
    family: 'gpt',
    generation: 'gpt-5',
    contextWindowTokens: 400_000,
    maxOutput: 272_000,
    releasedAt: '2025-10-06',
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 15,
      textOutput: 120,
    },
  },
  {
    id: 'gpt-audio',
    displayName: 'GPT Audio',
    description: 'GPT Audio 是支持音频输入/输出的通用对话模型，可通过 Chat Completions API 使用。',
    family: 'gpt',
    generation: 'gpt-audio',
    contextWindowTokens: 128_000,
    maxOutput: 16_384,
    releasedAt: '2025-08-28',
    abilities: {
      functionCall: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 2.5,
      textOutput: 10,
    },
  },
  {
    id: 'gpt-5',
    displayName: 'GPT-5',
    description: 'OpenAI 的 GPT-5 —— 旗舰模型，具备先进推理与多模态能力。',
    family: 'gpt',
    generation: 'gpt-5',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2025-08-07',
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.25,
      textOutput: 10,
      textInputCacheRead: 0.125,
    },
  },
  {
    id: 'gpt-5-chat-latest',
    displayName: 'GPT-5 Chat',
    description: 'GPT-5 模型用于 ChatGPT，结合强大的理解与生成能力，适用于对话类应用。',
    family: 'gpt',
    generation: 'gpt-5',
    contextWindowTokens: 400_000,
    maxOutput: 128_000,
    releasedAt: '2025-08-07',
    abilities: {
      vision: true,
    },
    pricing: {
      currency: 'USD',
      textInput: 1.25,
      textOutput: 10,
      textInputCacheRead: 0.125,
    },
  },
]

const byId = new Map(openaiChatModels.map((m) => [m.id, m]))

export const getOpenAIModel = (id: string) => byId.get(id)
