import { readFile } from 'node:fs/promises'

import debug from 'debug'
import * as xlsx from 'xlsx'

import type { DocumentPage, FileLoaderInterface } from '../../types'
import { promptTemplate } from './prompt'

const log = debug('file-loaders:excel')

/**
 * Converts sheet data (array of objects) to a Markdown table string.
 * Handles empty sheets and escapes pipe characters.
 */
function sheetToMarkdownTable(jsonData: Record<string, any>[]): string {
  log('开始将工作表数据转换为 Markdown 表格，数据行数：%d', jsonData?.length || 0)
  if (!jsonData || jsonData.length === 0) {
    log('工作表为空，返回空表提示')
    return '*Sheet is empty or contains no data.*'
  }

  // Ensure all rows have the same keys based on the first row, handle potentially sparse data
  const headers = Object.keys(jsonData[0] || {})
  log('工作表列名：%O', headers)
  if (headers.length === 0) {
    log('工作表未检测到列名，返回空表提示')
    return '*Sheet has headers but no data.*'
  }

  const headerRow = `| ${headers.join(' | ')} |`
  const separatorRow = `| ${headers.map(() => '---').join(' | ')} |`

  log('正在构建 Markdown 表格内容')
  const dataRows = jsonData
    .map((row) => {
      const cells = headers.map((header) => {
        const value = row[header]
        // Handle null/undefined and escape pipe characters within cells
        const cellContent = value === null || value === undefined ? '' : String(value).replaceAll('|', '\\|')
        return cellContent.trim() // Trim whitespace from cells
      })
      return `| ${cells.join(' | ')} |`
    })
    .join('\n')

  const result = `${headerRow}\n${separatorRow}\n${dataRows}`
  log('Markdown 表格创建完成，字符数：%d', result.length)
  return result
}

/**
 * Loads Excel files (.xlsx, .xls) using the 'xlsx' library.
 * Each sheet becomes a DocumentPage containing a Markdown table generated by sheetToMarkdownTable.
 */
export class ExcelLoader implements FileLoaderInterface {
  async loadPages(filePath: string): Promise<DocumentPage[]> {
    log('开始加载 Excel 文件：%s', filePath)
    const pages: DocumentPage[] = []
    try {
      // Use readFile for async operation compatible with other loaders
      log('正在读取 Excel 文件（Buffer）')
      const dataBuffer = await readFile(filePath)
      log('Excel 文件读取完成，大小：%d 字节', dataBuffer.length)

      log('正在解析 Excel 工作簿')
      const workbook = xlsx.read(dataBuffer, { type: 'buffer' })
      log('Excel 工作簿解析完成，包含 %d 个工作表', workbook.SheetNames.length)

      for (const sheetName of workbook.SheetNames) {
        log('正在处理工作表：%s', sheetName)
        const worksheet = workbook.Sheets[sheetName]
        // Use sheet_to_json to get array of objects for our custom markdown function
        const jsonData = xlsx.utils.sheet_to_json<Record<string, any>>(worksheet, {
          // Get formatted strings, not raw values
          defval: '',
          raw: false, // Use empty string for blank cells
        })
        log('工作表“%s”已转换为对象数组，数据行数：%d', sheetName, jsonData.length)

        // Convert to markdown using YOUR helper function
        const tableMarkdown = sheetToMarkdownTable(jsonData)

        const lines = tableMarkdown.split('\n')
        const lineCount = lines.length
        const charCount = tableMarkdown.length
        log('工作表“%s”已转换为 Markdown，行数：%d，字符数：%d', sheetName, lineCount, charCount)

        pages.push({
          // Trim whitespace
          charCount,
          lineCount,
          metadata: {
            sheetName,
          },
          pageContent: tableMarkdown.trim(),
        })
        log('工作表“%s”已添加为文档页面', sheetName)
      }

      if (pages.length === 0) {
        log('Excel 文件未包含工作表，创建空错误页面')
        pages.push({
          charCount: 0,
          lineCount: 0,
          metadata: {
            error: 'Excel file contains no sheets.',
          },
          pageContent: '',
        })
      }

      log('Excel 文件加载完成，共生成 %d 个文档页面', pages.length)
      return pages
    } catch (e) {
      const error = e as Error
      log('Excel 文件加载失败：%O', error)
      console.error(`Excel 文件加载失败（${filePath}）：${error.message}`)
      const errorPage: DocumentPage = {
        charCount: 0,
        lineCount: 0,
        metadata: {
          error: `Failed to load Excel file: ${error.message}`,
        },
        pageContent: '',
      }
      log('已为加载失败的 Excel 文件创建错误页面')
      return [errorPage]
    }
  }

  /**
   * Aggregates content from Excel sheets (Markdown tables).
   * Adds the sheet name as a header before each table.
   * @param pages Array of DocumentPage objects from loadPages.
   * @returns Aggregated content as a string.
   */
  async aggregateContent(pages: DocumentPage[]): Promise<string> {
    log('正在聚合 %d 个 Excel 文档页面的内容', pages.length)
    const result = promptTemplate(pages)

    log('Excel 内容聚合完成，字符数：%d', result.length)
    return result
  }
}
