/**
 * Curated community skills. Pick entries from scripts/community/generated/skills.data.ts
 * (`pnpm skills:sync`). Sync does not overwrite this file.
 */
import type { DiscoverSkillItem } from '@/features/community/types'

export const COMMUNITY_SKILLS_DATA = [
  {
    "author": "openclaw",
    "category": "coding-agents-ides",
    "description": "Captures learnings, errors, and corrections to enable continuous improvement. Use when: (1) A command or operation fails unexpectedly, (2) User corrects Claude ('No, that's wrong...', 'Actually...'), (3) User requests a capability that doesn't exist, (4) An external API or tool fails, (5) Claude realizes its knowledge is outdated or incorrect, (6) A better approach is discovered for a recurring task. Also review learnings before major tasks.",
    "identifier": "openclaw-skills-self-improving-agent-1-0-0",
    "name": "self-improvement",
    "updatedAt": "2026-09-16T23:37:18.192Z",
    "commentCount": 116,
    "createdAt": "2026-02-17T04:12:47.272Z",
    "github": {
      "forks": 758,
      "stars": 2596,
      "url": "https://github.com/openclaw/skills",
      "watchers": 28
    },
    "homepage": "https://github.com/openclaw/skills/tree/main/skills/dc-acronym/self-improving-agent-1-0-0",
    "icon": "https://github.com/openclaw.png",
    "installCount": 1887,
    "ratingAvg": 4.88,
    "resourcesCount": 3,
    "version": "1.0.4"
  },
  {
    "author": "openclaw",
    "category": "coding-agents-ides",
    "description": "创建、编辑、改进或审计 AgentSkills。在从头创建新技能时，或在被要求改进、审查、审计、整理或清理现有技能或 SKILL.md 文件时使用。也用于编辑或重构技能目录（将文件移动到 references/ 或 scripts/、删除过时内容、根据 AgentSkills 规范进行验证）。在出现类似“创建技能”、“撰写技能”、“整理技能”、“改进此技能”、“审查该技能”、“清理该技能”、“审计该技能”等短语时触发。",
    "identifier": "openclaw-openclaw-skill-creator",
    "name": "skill-creator",
    "updatedAt": "2026-09-22T04:55:49.606Z",
    "commentCount": 37,
    "createdAt": "2026-02-12T12:42:48.903Z",
    "github": {
      "forks": 67078,
      "stars": 340209,
      "url": "https://github.com/openclaw/openclaw",
      "watchers": 1688
    },
    "homepage": "https://github.com/openclaw/openclaw/tree/main/skills/skill-creator",
    "icon": "https://github.com/openclaw.png",
    "installCount": 1522,
    "license": "Apache-2.0",
    "ratingAvg": 4.93,
    "resourcesCount": 6,
    "version": "1.0.2"
  },
  {
    "author": "affaan-m",
    "category": "web-frontend-development",
    "description": "创建具有高设计质量的、可投入生产的前端界面。适用于用户要求构建网页组件、页面或应用程序，并且视觉方向与代码质量同等重要的场景。",
    "identifier": "affaan-m-everything-claude-code-frontend-design",
    "name": "frontend-design",
    "updatedAt": "2026-09-16T23:37:33.156Z",
    "commentCount": 103,
    "createdAt": "2026-04-06T22:01:44.578Z",
    "github": {
      "forks": 21687,
      "stars": 142573,
      "url": "https://github.com/affaan-m/everything-claude-code",
      "watchers": 780
    },
    "homepage": "https://github.com/affaan-m/everything-claude-code/tree/main/skills/frontend-design",
    "icon": "https://github.com/affaan-m.png",
    "installCount": 1724,
    "ratingAvg": 4.92,
    "version": "1.0.2"
  },
  {
    "author": "Patvscode",
    "category": "devops-cloud",
    "description": "在变更进行中决定多频繁重新检查关键工作（服务、代理、运行时）的轻量级分诊工具。用于避免忘记脆弱的任务。",
    "identifier": "patvscode-all_openclaw_agents-reliability-checkback",
    "name": "reliability-checkback",
    "updatedAt": "2026-09-16T18:57:59.299Z",
    "commentCount": 0,
    "createdAt": "2026-03-03T15:40:56.681Z",
    "github": {
      "forks": 0,
      "stars": 1,
      "url": "https://github.com/Patvscode/All_Openclaw_agents",
      "watchers": 0
    },
    "homepage": "https://github.com/Patvscode/All_Openclaw_agents/tree/main/snapshots/20260302_214359/workspace-max/skills/reliability-checkback",
    "icon": "https://github.com/Patvscode.png",
    "installCount": 510,
    "version": "1.0.405"
  },
  {
    "author": "Panniantong",
    "category": "search-research",
    "description": "为你的 AI 代理提供看遍全网的“眼睛”。可搜索并阅读 16 个平台：Twitter/X、Reddit、YouTube、GitHub、哔哩哔哩（B站）、小红书、抖音、微博、微信文章、小宇宙播客、LinkedIn、Instagram、V2EX、RSS、Exa 网页搜索以及任意网页。8 个通道为零配置。适用于用户要求在任何受支持平台上搜索、阅读或交互时，分享 URL，或要求网页搜索时使用。触发词：\"搜推特\", \"搜小红书\", \"看视频\", \"搜一下\", \"上网搜\", \"帮我查\", \"搜索 Twitter\", \"YouTube 字幕/转录\", \"搜索 Reddit\", \"读取此链接\", \"B站\", \"bilibili\", \"抖音视频\", \"微信文章\", \"公众号\", \"微博\", \"V2EX\", \"小宇宙\", \"播客\", \"网页搜索\", \"研究\", \"帮我安装\"。",
    "identifier": "panniantong-agent-reach-skill",
    "name": "agent-reach",
    "updatedAt": "2026-09-16T23:37:25.441Z",
    "commentCount": 38,
    "createdAt": "2026-03-08T06:32:21.139Z",
    "github": {
      "forks": 735,
      "stars": 10205,
      "url": "https://github.com/Panniantong/Agent-Reach",
      "watchers": 29
    },
    "homepage": "https://github.com/Panniantong/Agent-Reach/tree/main/agent_reach/skill",
    "icon": "https://github.com/Panniantong.png",
    "installCount": 1886,
    "ratingAvg": 4.37,
    "version": "1.0.2"
  },
  {
    "author": "vercel-labs",
    "category": "browser-automation",
    "description": "用于 AI 代理的浏览器自动化 CLI。当用户需要与网站交互时使用，包括导航页面、填写表单、点击按钮、截屏、提取数据、测试 Web 应用或自动执行任何浏览器任务。触发示例包括 \"打开网站\"、\"填写表单\"、\"点击按钮\"、\"截取屏幕\"、\"从页面抓取数据\"、\"测试此 Web 应用\"、\"登录站点\"、\"自动化浏览器操作\"，或任何需要以编程方式进行网页交互的任务。",
    "identifier": "vercel-labs-agent-browser-agent-browser",
    "name": "agent-browser",
    "updatedAt": "2026-09-16T17:20:47.665Z",
    "commentCount": 7,
    "createdAt": "2026-02-12T13:35:02.501Z",
    "github": {
      "forks": 1161,
      "stars": 19847,
      "url": "https://github.com/vercel-labs/agent-browser",
      "watchers": 52
    },
    "homepage": "https://github.com/vercel-labs/agent-browser/tree/main/skills/agent-browser",
    "icon": "https://github.com/vercel-labs.png",
    "installCount": 1385,
    "ratingAvg": 4.88,
    "resourcesCount": 10,
    "version": "1.0.3"
  },
  {
    "author": "firecrawl",
    "category": "browser-automation",
    "description": "通过 Firecrawl CLI 实现的网页爬取、搜索、抓取和浏览器自动化。每当用户想要在网上搜索、查找文章、研究某个主题、在线查资料、抓取网页、从 URL 获取内容、从网站提取数据、爬取文档、下载站点，或与需要点击或登录的页面交互时，都应使用此技能。也在他们说“抓取此页面”、“从……提取内容”、“获取 https:// 开头的页面”或提到对外部网站进行抓取时使用。该工具提供实时网页搜索、整页内容抽取和云端浏览器自动化——是 Claude 原生内置工具无法实现的能力。不要在本地文件操作、git 命令、部署或代码编辑任务时触发。",
    "identifier": "firecrawl-cli-firecrawl-cli",
    "name": "firecrawl",
    "updatedAt": "2026-09-21T17:55:38.740Z",
    "commentCount": 2,
    "createdAt": "2026-02-17T11:41:31.419Z",
    "github": {
      "forks": 28,
      "stars": 191,
      "url": "https://github.com/firecrawl/cli",
      "watchers": 2
    },
    "homepage": "https://github.com/firecrawl/cli/tree/main/skills/firecrawl-cli",
    "icon": "https://github.com/firecrawl.png",
    "installCount": 339,
    "ratingAvg": 4.5,
    "resourcesCount": 2,
    "version": "1.0.4"
  },
  {
    "author": "MiniMax-AI",
    "category": "productivity-tasks",
    "description": "生成、编辑和读取 PowerPoint 演示文稿。可使用 PptxGenJS 从头创建（封面、目录、正文、章节分隔、总结幻灯片），通过 XML 工作流编辑现有 PPTX，或使用 markitdown 提取文本。触发词：PPT、PPTX、PowerPoint、演示文稿、幻灯片、幻灯片集、幻灯片。",
    "identifier": "minimax-ai-skills-pptx-generator",
    "name": "pptx-generator",
    "updatedAt": "2026-09-22T03:39:16.016Z",
    "commentCount": 5,
    "createdAt": "2026-03-22T15:11:22.040Z",
    "github": {
      "forks": 54,
      "stars": 1157,
      "url": "https://github.com/MiniMax-AI/skills",
      "watchers": 3
    },
    "homepage": "https://github.com/MiniMax-AI/skills/tree/main/skills/pptx-generator",
    "icon": "https://github.com/MiniMax-AI.png",
    "installCount": 902,
    "license": "MIT",
    "ratingAvg": 4.57,
    "resourcesCount": 5,
    "version": "1.0.1"
  },
  {
    "author": "openclaw",
    "category": "ai-llms",
    "description": "Transform AI agents from task-followers into proactive partners that anticipate needs and continuously improve. Now with WAL Protocol, Working Buffer, Autonomous Crons, and battle-tested patterns. Part of the Hal Stack 🦞",
    "identifier": "openclaw-skills-proactive-agent",
    "name": "proactive-agent",
    "updatedAt": "2026-09-16T23:48:29.020Z",
    "commentCount": 69,
    "createdAt": "2026-02-17T13:56:39.856Z",
    "github": {
      "forks": 759,
      "stars": 2600,
      "url": "https://github.com/openclaw/skills",
      "watchers": 28
    },
    "homepage": "https://github.com/openclaw/skills/tree/main/skills/halthelobster/proactive-agent",
    "icon": "https://github.com/openclaw.png",
    "installCount": 1627,
    "isFeatured": true,
    "ratingAvg": 4.88,
    "resourcesCount": 13,
    "version": "3.1.0"
  },
  {
    "author": "davila7",
    "category": "ai-llms",
    "description": "将文件和办公文档转换为 Markdown。支持 PDF、DOCX、PPTX、XLSX、图像（含 OCR）、音频（含转录）、HTML、CSV、JSON、XML、ZIP、YouTube 链接、EPUB 等。",
    "identifier": "davila7-claude-code-templates-markitdown",
    "name": "markitdown",
    "updatedAt": "2026-09-19T02:51:57.375Z",
    "commentCount": 1,
    "createdAt": "2026-02-12T13:24:14.137Z",
    "github": {
      "forks": 2083,
      "stars": 22008,
      "url": "https://github.com/davila7/claude-code-templates",
      "watchers": 144
    },
    "homepage": "https://github.com/davila7/claude-code-templates/tree/main/cli-tool/components/skills/scientific/markitdown",
    "icon": "https://github.com/davila7.png",
    "installCount": 252,
    "license": "MIT",
    "ratingAvg": 5,
    "resourcesCount": 12,
    "version": "1.0.2"
  },
  {
    "author": "bytedance",
    "category": "cli-utilities",
    "description": "Helps users discover and install agent skills when they ask questions like \"how do I do X\", \"find a skill for X\", \"is there a skill that can...\", or express interest in extending capabilities. This skill should be used when the user is looking for functionality that might exist as an installable skill.",
    "identifier": "bytedance-deer-flow-find-skills",
    "name": "find-skills",
    "updatedAt": "2026-09-17T01:16:25.294Z",
    "commentCount": 86,
    "createdAt": "2026-03-11T20:35:15.793Z",
    "github": {
      "forks": 3496,
      "stars": 29267,
      "url": "https://github.com/bytedance/deer-flow",
      "watchers": 143
    },
    "homepage": "https://github.com/bytedance/deer-flow/tree/main/skills/public/find-skills",
    "icon": "https://github.com/bytedance.png",
    "installCount": 1918,
    "ratingAvg": 4.78,
    "resourcesCount": 1,
    "version": "1.0.1"
  },
  {
    "author": "openclaw",
    "category": "cli-utilities",
    "description": "通过 wttr.in 或 Open-Meteo 获取当前天气和预报。使用场景：用户询问任意地点的天气、气温或预报时。非适用场景：历史天气数据、重大气象警报或详细气象分析。无需 API 密钥。",
    "identifier": "openclaw-openclaw-weather",
    "name": "weather",
    "updatedAt": "2026-09-21T08:35:58.827Z",
    "commentCount": 7,
    "createdAt": "2026-02-12T13:11:45.212Z",
    "github": {
      "forks": 67078,
      "stars": 340209,
      "url": "https://github.com/openclaw/openclaw",
      "watchers": 1688
    },
    "homepage": "https://github.com/openclaw/openclaw/tree/main/skills/weather",
    "icon": "https://github.com/openclaw.png",
    "installCount": 760,
    "isFeatured": true,
    "ratingAvg": 4.89,
    "version": "1.0.2"
  },
  {
    "author": "openclaw",
    "category": "git-github",
    "description": "通过 `gh` CLI 执行 GitHub 操作：issues、PR、CI 运行、代码审查、API 查询。适用场景：(1) 检查 PR 状态或 CI，(2) 创建/评论 issue，(3) 列表/过滤 PR 或 issue，(4) 查看运行日志。不适用于：需要手动浏览器流程的复杂网页 UI 交互（有浏览器工具时请使用），跨大量仓库的批量操作（请用 `gh api` 编写脚本），或 `gh auth` 未配置时。",
    "identifier": "openclaw-openclaw-github",
    "name": "github",
    "updatedAt": "2026-09-16T18:44:36.244Z",
    "commentCount": 2,
    "createdAt": "2026-02-12T13:12:10.959Z",
    "github": {
      "forks": 67078,
      "stars": 340209,
      "url": "https://github.com/openclaw/openclaw",
      "watchers": 1688
    },
    "homepage": "https://github.com/openclaw/openclaw/tree/main/skills/github",
    "icon": "https://github.com/openclaw.png",
    "installCount": 791,
    "isFeatured": true,
    "ratingAvg": 4.25,
    "version": "1.0.2"
  },
  {
    "author": "openclaw",
    "category": "image-video-generation",
    "description": "通过 Gemini 3 Pro Image（Nano Banana Pro）生成或编辑图像。",
    "identifier": "openclaw-openclaw-nano-banana-pro",
    "name": "nano-banana-pro",
    "updatedAt": "2026-09-16T05:40:08.977Z",
    "commentCount": 5,
    "createdAt": "2026-02-12T13:11:43.602Z",
    "github": {
      "forks": 49371,
      "stars": 257537,
      "url": "https://github.com/openclaw/openclaw",
      "watchers": 1342
    },
    "homepage": "https://github.com/openclaw/openclaw/tree/main/skills/nano-banana-pro",
    "icon": "https://github.com/openclaw.png",
    "installCount": 1070,
    "isFeatured": true,
    "ratingAvg": 4.2,
    "resourcesCount": 1,
    "version": "1.0.2"
  },
  {
    "author": "davila7",
    "category": "communication",
    "description": "Remove signs of AI-generated writing from text. Use when editing or reviewing\ntext to make it sound more natural and human-written. Based on Wikipedia's\ncomprehensive \"Signs of AI writing\" guide. Detects and fixes patterns including:\ninflated symbolism, promotional language, superficial -ing analyses, vague\nattributions, em dash overuse, rule of three, AI vocabulary words, negative\nparallelisms, and excessive conjunctive phrases.\n\nCredits: Original skill by @blader - https://github.com/blader/humanizer",
    "identifier": "davila7-claude-code-templates-humanizer",
    "name": "humanizer",
    "updatedAt": "2026-09-16T23:37:42.925Z",
    "commentCount": 39,
    "createdAt": "2026-02-12T13:32:27.891Z",
    "github": {
      "forks": 1878,
      "stars": 20164,
      "url": "https://github.com/davila7/claude-code-templates"
    },
    "homepage": "https://github.com/davila7/claude-code-templates/tree/main/cli-tool/components/skills/productivity/humanizer",
    "icon": "https://github.com/davila7.png",
    "installCount": 1365,
    "ratingAvg": 5,
    "resourcesCount": 1,
    "version": "2.1.1"
  },
  {
    "author": "ComposioHQ",
    "category": "transportation",
    "description": "Automate Google Maps tasks via Rube MCP (Composio): geocode addresses, search places, get directions, compute route matrices, reverse geocode, autocomplete, get place details. Always search tools first for current schemas.",
    "identifier": "composiohq-awesome-claude-skills-google-maps-automation",
    "name": "google-maps-automation",
    "updatedAt": "2026-09-16T02:39:11.663Z",
    "commentCount": 0,
    "createdAt": "2026-03-11T09:10:12.913Z",
    "github": {
      "forks": 4301,
      "stars": 42914,
      "url": "https://github.com/ComposioHQ/awesome-claude-skills",
      "watchers": 299
    },
    "homepage": "https://github.com/ComposioHQ/awesome-claude-skills/tree/master/composio-skills/google-maps-automation",
    "icon": "https://github.com/ComposioHQ.png",
    "installCount": 162,
    "version": "1.0.1"
  },
  {
    "author": "anthropics",
    "category": "pdf-documents",
    "description": "任何涉及 .pptx 或 .potx 文件（作为输入、输出或两者）的情况都可以使用此技能。适用场景包括：创建幻灯片集、宣讲稿或演示文稿；从任何 .pptx 或 .potx 文件读取、解析或提取文本（即使提取内容将用于其他地方，如邮件或摘要）；编辑、修改或更新现有演示文稿；合并或拆分幻灯片文件；处理模板（.potx）、布局、演讲者备注或评论。只要用户提到“幻灯片集”、“幻灯片”、“演示文稿”，或引用 .pptx 或 .potx 文件名，不论他们之后打算如何使用内容，都应触发该技能。如果需要打开、创建或接触 .pptx 或 .potx 文件，请使用此技能。",
    "identifier": "anthropics-skills-pptx",
    "name": "pptx",
    "updatedAt": "2026-09-22T04:53:52.348Z",
    "commentCount": 75,
    "createdAt": "2026-02-12T13:15:02.445Z",
    "github": {
      "forks": 20869,
      "stars": 176292,
      "url": "https://github.com/anthropics/skills",
      "watchers": 1127
    },
    "homepage": "https://github.com/anthropics/skills/tree/main/skills/pptx",
    "icon": "https://github.com/anthropics.png",
    "installCount": 3108,
    "isFeatured": true,
    "license": "Proprietary",
    "ratingAvg": 4.54,
    "resourcesCount": 55,
    "version": "1.0.5"
  },
  {
    "author": "anthropics",
    "category": "pdf-documents",
    "description": "当电子表格文件是主要输入或输出时，请使用此技能。也就是说，任何用户想要打开、读取、编辑或修复现有 .xlsx、.xlsm、.xltx、.csv 或 .tsv 文件（例如：添加列、计算公式、格式化、制图、清理混乱数据）；从头或从其他数据源创建新的电子表格；或在表格文件格式之间转换的任务均适用。尤其在用户按名称或路径引用某个电子表格文件时（即使是随意提及，例如 \"我的下载里的 xlsx\"）并希望对其执行操作或产出结果时要触发。另外，对于将混乱的表格数据文件（格式错误的行、错位的表头、垃圾数据）清理或重构为正规电子表格的情况也要触发。交付物必须是电子表格文件。主要交付物为 Word 文档、HTML 报告、独立 Python 脚本、数据库流水线或 Google Sheets API 集成时不要触发，即使涉及表格数据也不例外。",
    "identifier": "anthropics-skills-xlsx",
    "name": "xlsx",
    "updatedAt": "2026-09-22T04:54:50.143Z",
    "commentCount": 24,
    "createdAt": "2026-02-12T13:25:54.206Z",
    "github": {
      "forks": 20869,
      "stars": 176292,
      "url": "https://github.com/anthropics/skills",
      "watchers": 1127
    },
    "homepage": "https://github.com/anthropics/skills/tree/main/skills/xlsx",
    "icon": "https://github.com/anthropics.png",
    "installCount": 1459,
    "isFeatured": true,
    "license": "Proprietary",
    "ratingAvg": 4.69,
    "resourcesCount": 52,
    "version": "1.0.5"
  },
  {
    "author": "anthropics",
    "category": "pdf-documents",
    "description": "当用户想对 PDF 文件进行任何操作时，请使用此技能。这包括从 PDF 中阅读或提取文本/表格、将多个 PDF 合并为一个、拆分 PDF、旋转页面、添加水印、创建新 PDF、填写 PDF 表单、加密/解密 PDF、提取图像以及对扫描的 PDF 进行 OCR 以使其可搜索。如果用户提到 .pdf 文件或要求生成 PDF，请使用此技能。",
    "identifier": "anthropics-skills-pdf",
    "name": "pdf",
    "updatedAt": "2026-09-22T02:03:00.974Z",
    "commentCount": 61,
    "createdAt": "2026-02-12T13:14:12.911Z",
    "github": {
      "forks": 20869,
      "stars": 176292,
      "url": "https://github.com/anthropics/skills",
      "watchers": 1127
    },
    "homepage": "https://github.com/anthropics/skills/tree/main/skills/pdf",
    "icon": "https://github.com/anthropics.png",
    "installCount": 2609,
    "isFeatured": true,
    "license": "Proprietary",
    "ratingAvg": 4.96,
    "resourcesCount": 11,
    "version": "1.0.5"
  },
  {
    "author": "anthropics",
    "category": "pdf-documents",
    "description": "当用户想要创建、读取、编辑或操作 Word 文档（.docx 文件）或 Word 模板（.dotx 文件）时，请使用此技能。触发场景包括：任何提及“Word doc”、“word document”、“.docx”、“.dotx”，或请求生成具有目录、标题、页码或信头等格式的专业文档的情况。还应在从 .docx 或 .dotx 文件中提取或重组内容、在文档中插入或替换图像、在 Word 文件中执行查找与替换、处理修订或注释、或将内容转换为格式化良好的 Word 文档时使用。如果用户要求以 Word 或 .docx 文件形式交付“报告”、“备忘录”、“信件”、“模板”或类似成果，也请使用此技能。不要用于 PDF、电子表格、Google 文档或与文档生成无关的一般编码任务。",
    "identifier": "anthropics-skills-docx",
    "name": "docx",
    "updatedAt": "2026-09-22T02:02:56.643Z",
    "commentCount": 39,
    "createdAt": "2026-02-12T13:25:58.403Z",
    "github": {
      "forks": 20869,
      "stars": 176292,
      "url": "https://github.com/anthropics/skills",
      "watchers": 1127
    },
    "homepage": "https://github.com/anthropics/skills/tree/main/skills/docx",
    "icon": "https://github.com/anthropics.png",
    "installCount": 2228,
    "isFeatured": true,
    "license": "Proprietary",
    "ratingAvg": 4.9,
    "resourcesCount": 60,
    "version": "1.0.5"
  },
  {
    "author": "fore-vip",
    "category": "marketing-sales",
    "description": "批量推送 AI 产品。从外部来源（AI、搜索、GitHub 等）创建多个产品，不进行重复检查。",
    "identifier": "fore-vip-skills-product",
    "name": "product",
    "updatedAt": "2026-09-14T21:53:36.065Z",
    "commentCount": 0,
    "createdAt": "2026-03-31T04:02:09.440Z",
    "github": {
      "forks": 0,
      "stars": 0,
      "url": "https://github.com/fore-vip/skills",
      "watchers": 0
    },
    "homepage": "https://github.com/fore-vip/skills/tree/main/product",
    "icon": "https://github.com/fore-vip.png",
    "installCount": 389,
    "license": "MIT",
    "resourcesCount": 6,
    "version": "2.0.0"
  },
  {
    "author": "affaan-m",
    "category": "health-fitness",
    "description": "医疗应用中EMR/EHR的开发模式，涵盖临床安全、就诊工作流、处方生成、临床决策支持集成及以可访问性为先的医疗数据录入用户界面。",
    "identifier": "affaan-m-ecc-healthcare-emr-patterns",
    "name": "healthcare-emr-patterns",
    "updatedAt": "2026-09-16T02:10:03.480Z",
    "commentCount": 0,
    "createdAt": "2026-05-19T10:08:57.787Z",
    "github": {
      "forks": 28938,
      "stars": 186895,
      "url": "https://github.com/affaan-m/ECC",
      "watchers": 933
    },
    "homepage": "https://github.com/affaan-m/ECC/tree/main/docs/ja-JP/skills/healthcare-emr-patterns",
    "icon": "https://github.com/affaan-m.png",
    "installCount": 192,
    "version": "1.0.0"
  },
  {
    "author": "openclaw",
    "category": "media-streaming",
    "description": "High-quality voice synthesis with 9 personas, 11 languages, streaming, and voice cloning using Voice.ai API.",
    "identifier": "openclaw-skills-voice-ai-tts",
    "name": "voice-ai-tts",
    "updatedAt": "2026-09-15T07:34:47.933Z",
    "commentCount": 1,
    "createdAt": "2026-02-17T06:17:09.555Z",
    "github": {
      "forks": 356,
      "stars": 1069,
      "url": "https://github.com/openclaw/skills"
    },
    "homepage": "https://github.com/openclaw/skills/tree/main/skills/gizmogremlin/voice-ai-tts",
    "icon": "https://github.com/openclaw.png",
    "installCount": 289,
    "ratingAvg": 5,
    "resourcesCount": 4,
    "version": "1.0.1"
  },
  {
    "author": "openclaw",
    "category": "notes-pkm",
    "description": "处理 Obsidian 存储库（纯 Markdown 笔记），并通过 obsidian-cli 实现自动化。",
    "identifier": "openclaw-openclaw-obsidian",
    "name": "obsidian",
    "updatedAt": "2026-09-16T11:08:58.151Z",
    "commentCount": 14,
    "createdAt": "2026-02-12T13:11:28.910Z",
    "github": {
      "forks": 67078,
      "stars": 340209,
      "url": "https://github.com/openclaw/openclaw",
      "watchers": 1688
    },
    "homepage": "https://github.com/openclaw/openclaw/tree/main/skills/obsidian",
    "icon": "https://github.com/openclaw.png",
    "installCount": 1002,
    "isFeatured": true,
    "ratingAvg": 4.14,
    "version": "1.0.3"
  },
  {
    "author": "ComposioHQ",
    "category": "calendar-scheduling",
    "description": "Automate Cal tasks via Rube MCP (Composio). Always search tools first for current schemas.",
    "identifier": "composiohq-awesome-claude-skills-cal-automation",
    "name": "cal-automation",
    "updatedAt": "2026-09-16T02:34:41.961Z",
    "commentCount": 0,
    "createdAt": "2026-03-11T09:09:31.603Z",
    "github": {
      "forks": 4301,
      "stars": 42914,
      "url": "https://github.com/ComposioHQ/awesome-claude-skills",
      "watchers": 299
    },
    "homepage": "https://github.com/ComposioHQ/awesome-claude-skills/tree/master/composio-skills/cal-automation",
    "icon": "https://github.com/ComposioHQ.png",
    "installCount": 146,
    "version": "1.0.1"
  },
  {
    "author": "fore-vip",
    "category": "shopping-ecommerce",
    "description": "在 fore.vip 上创建单个 AI 产品并进行重复检查。内容可来自外部来源（AI 生成、搜索、GitHub、Product Hunt、用户对话等）。",
    "identifier": "fore-vip-skills-product-create",
    "name": "product-create",
    "updatedAt": "2026-09-13T23:01:14.553Z",
    "commentCount": 0,
    "createdAt": "2026-03-31T04:01:31.291Z",
    "github": {
      "forks": 0,
      "stars": 0,
      "url": "https://github.com/fore-vip/skills",
      "watchers": 0
    },
    "homepage": "https://github.com/fore-vip/skills/tree/main/product-create",
    "icon": "https://github.com/fore-vip.png",
    "installCount": 398,
    "license": "MIT",
    "resourcesCount": 1,
    "version": "1.0.0"
  },
  {
    "author": "openclaw",
    "category": "security-passwords",
    "description": "面向 AI 代理的安全优先技能审查工具。在从 ClawdHub、GitHub 或其他来源安装任何技能之前使用。检测潜在危险信号、权限范围和可疑模式。",
    "identifier": "openclaw-skills-skill-vetter",
    "name": "skill-vetter",
    "updatedAt": "2026-09-16T11:57:32.832Z",
    "commentCount": 181,
    "createdAt": "2026-02-17T13:14:41.683Z",
    "github": {
      "forks": 953,
      "stars": 3331,
      "url": "https://github.com/openclaw/skills",
      "watchers": 34
    },
    "homepage": "https://github.com/openclaw/skills/tree/main/skills/spclaudehome/skill-vetter",
    "icon": "https://github.com/openclaw.png",
    "installCount": 2747,
    "isFeatured": true,
    "ratingAvg": 4.86,
    "resourcesCount": 1,
    "version": "1.0.0"
  },
  {
    "author": "a18515373115-droid",
    "category": "personal-development",
    "description": "张雪峰的思维框架与表达方式。基于5本著作、15+篇权威媒体深度采访、\n30+条一手语录、11个关键决策记录和完整人生时间线的深度调研，\n提炼5个核心心智模型、8条决策启发式和完整的表达DNA。\n用途：作为思维顾问，用张雪峰的视角分析教育选择、职业规划、阶层流动等问题。\n当用户提到「用张雪峰的视角」「张雪峰会怎么看」「张雪峰模式」「雪峰视角」时使用。\n即使用户只是说「帮我用张雪峰的角度想想」「如果张雪峰会怎么说」「切换到张雪峰」也应触发。",
    "identifier": "a18515373115-droid-zhangxuefeng-skill",
    "name": "张雪峰-skill",
    "updatedAt": "2026-09-14T17:05:04.159Z",
    "commentCount": 2,
    "createdAt": "2026-04-08T16:02:12.292Z",
    "github": {
      "forks": 0,
      "stars": 0,
      "url": "https://github.com/a18515373115-droid/ZhangXueFeng-skill",
      "watchers": 0
    },
    "homepage": "https://github.com/a18515373115-droid/ZhangXueFeng-skill",
    "icon": "https://github.com/a18515373115-droid.png",
    "installCount": 259,
    "license": "MIT",
    "ratingAvg": 5,
    "resourcesCount": 10,
    "version": "2.0"
  },
  {
    "author": "openclaw",
    "category": "speech-transcription",
    "description": "使用 Whisper CLI 本地进行语音转文本（无需 API 密钥）。",
    "identifier": "openclaw-openclaw-openai-whisper",
    "name": "openai-whisper",
    "updatedAt": "2026-09-16T16:44:23.013Z",
    "commentCount": 7,
    "createdAt": "2026-02-12T13:11:33.449Z",
    "github": {
      "forks": 67078,
      "stars": 340209,
      "url": "https://github.com/openclaw/openclaw",
      "watchers": 1688
    },
    "homepage": "https://github.com/openclaw/openclaw/tree/main/skills/openai-whisper",
    "icon": "https://github.com/openclaw.png",
    "installCount": 622,
    "isFeatured": true,
    "ratingAvg": 4.13,
    "version": "1.0.2"
  },
  {
    "author": "openclaw",
    "category": "apple-apps-services",
    "description": "通过 macOS 上的 `memo` 命令行工具管理 Apple 备忘录（创建、查看、编辑、删除、搜索、移动和导出笔记）。当用户请求 OpenClaw 添加笔记、列出笔记、搜索笔记或管理笔记文件夹时使用。",
    "identifier": "openclaw-openclaw-apple-notes",
    "name": "apple-notes",
    "updatedAt": "2026-09-16T08:25:36.005Z",
    "commentCount": 2,
    "createdAt": "2026-02-12T13:11:08.189Z",
    "github": {
      "forks": 67078,
      "stars": 340209,
      "url": "https://github.com/openclaw/openclaw",
      "watchers": 1688
    },
    "homepage": "https://github.com/openclaw/openclaw/tree/main/skills/apple-notes",
    "icon": "https://github.com/openclaw.png",
    "installCount": 342,
    "ratingAvg": 5,
    "version": "1.0.3"
  },
  {
    "author": "openclaw",
    "category": "smart-home-iot",
    "description": "控制 Eight Sleep pod（状态、温度、闹钟、日程）。",
    "identifier": "openclaw-openclaw-eightctl",
    "name": "eightctl",
    "updatedAt": "2026-09-16T02:10:37.592Z",
    "commentCount": 0,
    "createdAt": "2026-02-12T13:11:30.390Z",
    "github": {
      "forks": 67078,
      "stars": 340209,
      "url": "https://github.com/openclaw/openclaw",
      "watchers": 1688
    },
    "homepage": "https://github.com/openclaw/openclaw/tree/main/skills/eightctl",
    "icon": "https://github.com/openclaw.png",
    "installCount": 256,
    "version": "1.0.3"
  },
  {
    "author": "wshobson",
    "category": "gaming",
    "description": "掌握 Godot 4 的 GDScript 设计模式，包括信号、场景、状态机和优化。适用于构建 Godot 游戏、实现游戏系统或学习 GDScript 的最佳实践。",
    "identifier": "wshobson-agents-godot-gdscript-patterns",
    "name": "godot-gdscript-patterns",
    "updatedAt": "2026-09-16T02:31:30.570Z",
    "commentCount": 8,
    "createdAt": "2026-02-12T13:17:52.528Z",
    "github": {
      "forks": 3318,
      "stars": 30327,
      "url": "https://github.com/wshobson/agents",
      "watchers": 307
    },
    "homepage": "https://github.com/wshobson/agents/tree/main/plugins/game-development/skills/godot-gdscript-patterns",
    "icon": "https://github.com/wshobson.png",
    "installCount": 359,
    "ratingAvg": 4.5,
    "version": "1.0.3"
  },
  {
    "author": "openclaw",
    "category": "clawdbot-tools",
    "description": "通过对 old.reddit.com 的网页抓取读取和搜索 Reddit 帖子。当 Clawdbot 需要浏览 Reddit 内容时使用 — 可读取子版块的帖子、搜索话题、监控特定社区。仅限只读，不进行发布或评论。",
    "identifier": "openclaw-skills-reddit-scraper",
    "name": "reddit",
    "updatedAt": "2026-09-16T07:14:24.063Z",
    "commentCount": 20,
    "createdAt": "2026-02-17T13:08:01.743Z",
    "github": {
      "forks": 598,
      "stars": 1907,
      "url": "https://github.com/openclaw/skills",
      "watchers": 22
    },
    "homepage": "https://github.com/openclaw/skills/tree/main/skills/javicasper/reddit-scraper",
    "icon": "https://github.com/openclaw.png",
    "installCount": 863,
    "ratingAvg": 4.1,
    "resourcesCount": 3,
    "version": "1.0.2"
  },
  {
    "author": "Aradotso",
    "category": "self-hosted-automation",
    "description": "```markdown",
    "identifier": "aradotso-trending-skills-awesome-hermes-agent",
    "name": "Awesome Hermes Agent",
    "updatedAt": "2026-09-15T15:53:19.444Z",
    "commentCount": 5,
    "createdAt": "2026-03-30T22:50:07.497Z",
    "github": {
      "forks": 3,
      "stars": 15,
      "url": "https://github.com/Aradotso/trending-skills",
      "watchers": 0
    },
    "homepage": "https://github.com/Aradotso/trending-skills/tree/main/skills/awesome-hermes-agent",
    "icon": "https://github.com/Aradotso.png",
    "installCount": 666,
    "ratingAvg": 4.29,
    "version": "1.0.1"
  },
  {
    "author": "LingoJack",
    "category": "ios-macos-development",
    "description": "iOS 应用 Swift 原生开发技能包；当用户描述开发 iOS 原生应用的需求时加载此技能。",
    "identifier": "lingojack-j-swift-ios-app-gen",
    "name": "swift-ios-app-gen",
    "updatedAt": "2026-09-16T11:30:41.508Z",
    "commentCount": 0,
    "createdAt": "2026-03-31T04:01:52.614Z",
    "github": {
      "forks": 0,
      "stars": 1,
      "url": "https://github.com/LingoJack/j",
      "watchers": 0
    },
    "homepage": "https://github.com/LingoJack/j/tree/main/assets/skills/swift-ios-app-gen",
    "icon": "https://github.com/LingoJack.png",
    "installCount": 351,
    "version": "1.0.1"
  },
  {
    "author": "modu-ai",
    "category": "moltbook",
    "description": "书籍章节正文草稿撰写——以“节”（单个章节段落）为单位写作，管理篇幅、处理引文，并自动按四种文体分支。接收书籍大纲设计器（book-outline-designer）提供的章节概要，完整撰写单个节从开头到结尾的稿件。提供实用（清晰·实操）、人文（叙事·文体）、技术（代码·图表）、小说（描写·视角）四类预设。自动计算以每页200字原稿纸为单位的页数，引用以脚注标注，整合图表与代码块占位。\n\n遇到以下请求时请务必使用此技能：\n- “章节正文写作”、“节落写作”、“稿件撰写”\n- “书籍正文”、“章正文”、“草稿写作”\n- “按类型文体”、“出版稿件写作”\n- “引用处理”、“脚注标注”、“插入图表”",
    "identifier": "modu-ai-cowork-plugins-book-chapter-writer",
    "name": "book-chapter-writer",
    "updatedAt": "2026-09-16T03:03:10.174Z",
    "commentCount": 0,
    "createdAt": "2026-05-18T04:05:24.819Z",
    "github": {
      "forks": 48,
      "stars": 200,
      "url": "https://github.com/modu-ai/cowork-plugins",
      "watchers": 1
    },
    "homepage": "https://github.com/modu-ai/cowork-plugins/tree/main/moai-book/skills/book-chapter-writer",
    "icon": "https://github.com/modu-ai.png",
    "installCount": 135,
    "resourcesCount": 1,
    "version": "2.10.0"
  },
  {
    "author": "davila7",
    "category": "data-analytics",
    "description": "分析 Excel 电子表格、创建透视表、生成图表并执行数据分析。在分析 Excel 文件、电子表格、表格式数据或 .xlsx 文件时使用。",
    "identifier": "davila7-claude-code-templates-excel-analysis",
    "name": "Excel Analysis",
    "updatedAt": "2026-09-16T05:38:49.702Z",
    "commentCount": 5,
    "createdAt": "2026-02-12T13:19:26.528Z",
    "github": {
      "forks": 2083,
      "stars": 22008,
      "url": "https://github.com/davila7/claude-code-templates",
      "watchers": 144
    },
    "homepage": "https://github.com/davila7/claude-code-templates/tree/main/cli-tool/components/skills/enterprise-communication/excel-analysis",
    "icon": "https://github.com/davila7.png",
    "installCount": 915,
    "ratingAvg": 4.71,
    "version": "1.0.2"
  },
  {
    "author": "sickn33",
    "category": "finance",
    "description": "构建金融模型，回测交易策略并分析市场数据。实现风险度量、投资组合优化和统计套利。对于量化金融、交易算法或风险分析，请积极主动地使用。",
    "identifier": "sickn33-antigravity-awesome-skills-quant-analyst",
    "name": "quant-analyst",
    "updatedAt": "2026-09-15T15:37:02.150Z",
    "commentCount": 6,
    "createdAt": "2026-02-12T13:43:44.130Z",
    "github": {
      "forks": 1752,
      "stars": 8567,
      "url": "https://github.com/sickn33/antigravity-awesome-skills"
    },
    "homepage": "https://github.com/sickn33/antigravity-awesome-skills/tree/main/skills/quant-analyst",
    "icon": "https://github.com/sickn33.png",
    "installCount": 418,
    "ratingAvg": 4.71,
    "version": "1.0.1"
  },
  {
    "author": "openclaw",
    "category": "agent-to-agent-protocols",
    "description": "A self-evolution engine for AI agents. Analyzes runtime history to identify improvements and applies protocol-constrained evolution.",
    "identifier": "openclaw-skills-capability-evolver",
    "name": "capability-evolver",
    "updatedAt": "2026-09-16T06:23:40.874Z",
    "commentCount": 49,
    "createdAt": "2026-02-17T04:18:05.857Z",
    "github": {
      "forks": 759,
      "stars": 2602,
      "url": "https://github.com/openclaw/skills",
      "watchers": 28
    },
    "homepage": "https://github.com/openclaw/skills/tree/main/skills/autogame-17/capability-evolver",
    "icon": "https://github.com/openclaw.png",
    "installCount": 1658,
    "isFeatured": true,
    "ratingAvg": 4.1,
    "resourcesCount": 75,
    "tags": [
      "meta",
      "ai",
      "self-improvement",
      "core"
    ],
    "version": "1.0.3"
  }
] as DiscoverSkillItem[]
