import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const src = path.join(root, 'dist')
const dest = path.join(root, 'public', '_spa')
const assetsSrc = path.join(src, 'assets')
const generatedTemplate = path.join(root, 'src', 'app', 'spa', 'spaHtmlTemplate.generated.ts')

if (!existsSync(src)) {
  console.error(`❌ SPA build output not found: ${src}`)
  process.exit(1)
}

const indexHtmlPath = path.join(src, 'index.html')
if (!existsSync(indexHtmlPath)) {
  console.error(`❌ SPA index.html not found: ${indexHtmlPath}`)
  process.exit(1)
}

if (!existsSync(assetsSrc)) {
  console.error(`❌ SPA assets not found: ${assetsSrc}`)
  process.exit(1)
}

const indexHtml = readFileSync(indexHtmlPath, 'utf-8')

rmSync(dest, { force: true, recursive: true })
mkdirSync(path.join(dest, 'assets'), { recursive: true })
cpSync(assetsSrc, path.join(dest, 'assets'), { recursive: true })

// Keep index.html out of public — served by `src/app/spa/[[...path]]/route.ts` with config injection.
writeFileSync(
  generatedTemplate,
  `/* auto-generated by scripts/copySpaBuild.mjs — do not edit; discard local diffs (keep stub in git) */\nexport default ${JSON.stringify(indexHtml)}\n`,
  'utf-8',
)

console.log(`✅ Copied SPA assets: ${assetsSrc} → ${path.join(dest, 'assets')}`)
console.log(`✅ Wrote SPA HTML template: ${generatedTemplate}`)
