/**
 * Sync community agents from LobeHub agents-index CDN (Legacy Community).
 *
 * Usage: pnpm agents:sync
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const AGENTS_INDEX_URL =
  'https://registry.npmmirror.com/@lobehub/agents-index/v1/files/public'
const LOCALE = 'zh-CN'
const PER_CATEGORY = 30
const CONCURRENCY = 10

const BUSINESS_CATEGORIES = [
  'academic',
  'career',
  'copywriting',
  'design',
  'education',
  'emotions',
  'entertainment',
  'games',
  'general',
  'life',
  'marketing',
  'office',
  'programming',
  'translation',
] as const

type BusinessCategory = (typeof BUSINESS_CATEGORIES)[number]

type IndexAgent = {
  author?: string
  createdAt?: string
  identifier: string
  knowledgeCount?: number
  meta?: {
    avatar?: string
    category?: string
    description?: string
    title?: string
  }
  pluginCount?: number
  tokenUsage?: number
}

type DetailAgent = {
  config?: {
    systemRole?: string
  }
}

type DiscoverAgentItem = {
  author: string
  avatar: string
  category: BusinessCategory
  createdAt: string
  description: string
  identifier: string
  knowledgeCount?: number
  pluginCount?: number
  systemRole: string
  title: string
  tokenUsage?: number
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT_PATH = join(__dirname, '../src/const/community/agents.data.ts')

const isBusinessCategory = (value: string | undefined): value is BusinessCategory =>
  Boolean(value && (BUSINESS_CATEGORIES as readonly string[]).includes(value))

async function mapPool<T, R>(
  items: T[],
  concurrency: number,
  mapper: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
  const results = new Array<R>(items.length)
  let next = 0

  const workers = Array.from({ length: Math.min(concurrency, items.length) }, async () => {
    while (next < items.length) {
      const index = next++
      results[index] = await mapper(items[index], index)
    }
  })

  await Promise.all(workers)
  return results
}

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url, { redirect: 'follow' })
  if (!res.ok) {
    throw new Error(`GET ${url} failed: ${res.status} ${res.statusText}`)
  }
  return (await res.json()) as T
}

async function fetchSystemRole(identifier: string): Promise<string> {
  const url = `${AGENTS_INDEX_URL}/${identifier}.${LOCALE}.json`
  try {
    const detail = await fetchJson<DetailAgent>(url)
    return detail.config?.systemRole ?? ''
  } catch (error) {
    console.warn(`[agents:sync] detail failed for ${identifier}:`, error)
    return ''
  }
}

async function main() {
  console.log('[agents:sync] fetching index…')
  const index = await fetchJson<{ agents: IndexAgent[] }>(
    `${AGENTS_INDEX_URL}/index.${LOCALE}.json`,
  )
  const agents = index.agents ?? []
  console.log(`[agents:sync] index size: ${agents.length}`)

  const selected: IndexAgent[] = []
  const counts: Record<string, number> = {}

  for (const category of BUSINESS_CATEGORIES) {
    const group = agents
      .filter((agent) => agent.meta?.category === category)
      .slice(0, PER_CATEGORY)
    counts[category] = group.length
    selected.push(...group)
  }

  console.log('[agents:sync] per category:', counts)
  console.log(`[agents:sync] fetching ${selected.length} details (concurrency=${CONCURRENCY})…`)

  const items = await mapPool(selected, CONCURRENCY, async (agent) => {
    const category = agent.meta?.category
    if (!isBusinessCategory(category)) {
      throw new Error(`unexpected category for ${agent.identifier}: ${category}`)
    }

    const systemRole = await fetchSystemRole(agent.identifier)

    const item: DiscoverAgentItem = {
      author: agent.author ?? 'unknown',
      avatar: agent.meta?.avatar ?? '🤖',
      category,
      createdAt: agent.createdAt ?? '',
      description: agent.meta?.description ?? '',
      identifier: agent.identifier,
      systemRole,
      title: agent.meta?.title ?? agent.identifier,
    }

    if (typeof agent.knowledgeCount === 'number') item.knowledgeCount = agent.knowledgeCount
    if (typeof agent.pluginCount === 'number') item.pluginCount = agent.pluginCount
    if (typeof agent.tokenUsage === 'number') item.tokenUsage = agent.tokenUsage

    return item
  })

  const missingRole = items.filter((item) => !item.systemRole).length
  if (missingRole > 0) {
    console.warn(`[agents:sync] ${missingRole} agents missing systemRole`)
  }

  const header = [
    '/**',
    ' * Auto-generated by `pnpm agents:sync` from LobeHub `@lobehub/agents-index`.',
    ' * Do not edit manually.',
    ' */',
    "import type { DiscoverAgentItem } from '@/features/community/types'",
    '',
    'export const COMMUNITY_AGENTS_DATA =',
  ].join('\n')

  const body = JSON.stringify(items, null, 2)
  // String enum categories from JSON are asserted — TS does not widen '"academic"' to AssistantCategory.
  const content = `${header} ${body} as DiscoverAgentItem[]\n`

  writeFileSync(OUT_PATH, content, 'utf8')
  console.log(`[agents:sync] wrote ${items.length} agents → ${OUT_PATH}`)
}

main().catch((error) => {
  console.error('[agents:sync] failed:', error)
  process.exit(1)
})
